name: Terraform Plan and Apply

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Enter environment (e.g., dev or prod)'
        required: true
        default: 'dev'

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        working-directory: ./project-root/envs/${{ github.event.inputs.environment }}
        run: terraform init -backend-config=../../backend/backend-${{ github.event.inputs.environment }}.tf

      - name: Terraform Plan
        working-directory: ./project-root/envs/${{ github.event.inputs.environment }}
        run: |
          echo "Running plan for environment: ${{ github.event.inputs.environment }}"
          terraform plan -var-file=${{ github.event.inputs.environment }}.tfvars
