
name: Terraform Multi-Env Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Enter environment (dev or prod)'
        required: true
        default: 'dev'

jobs:
  terraform:
    name: Terraform Plan and Apply
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_IN_AUTOMATION: true

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: |
          cd project-root/envs/${{ github.event.inputs.environment }}
          terraform init -backend-config=../../backend/backend-${{ github.event.inputs.environment }}.tf

      - name: Terraform Plan
        run: |
          cd project-root/envs/${{ github.event.inputs.environment }}
          terraform plan -var-file=${{ github.event.inputs.environment }}.tfvars

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: |
          cd project-root/envs/${{ github.event.inputs.environment }}
          terraform apply -auto-approve -var-file=${{ github.event.inputs.environment }}.tfvars
