name: Terraform Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Enter the environment (dev or prod)"
        required: true
        default: "dev"

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID:     ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      ENV_DIR: project-root/envs/${{ github.event.inputs.environment }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: |
          cd $ENV_DIR
          terraform init -input=false

      - name: Terraform Validate
        run: |
          cd $ENV_DIR
          terraform validate

      - name: Terraform Plan
        run: |
          cd $ENV_DIR
          terraform plan -var-file="${{ github.event.inputs.environment }}.tfvars"

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: |
          cd $ENV_DIR
          terraform apply -auto-approve -var-file="${{ github.event.inputs.environment }}.tfvars"
